// src/theme.js

export const THEMES = {
  'minimal-white': {
    name: 'Minimal White',
    free: true,
    bg: '#FAF7F2',
    surface: '#FFFFFF',
    surfaceAlt: '#F2EFE8',
    ink: '#29261B',
    muted: 'rgba(41,38,27,0.55)',
    faint: 'rgba(41,38,27,0.08)',
    accent: '#F4B6B6',
    accentInk: '#7A3838',
    cardFront: '#FFFFFF',
    cardBack: '#FFF8F0',
    glyph: null,
    errorRed: '#E5484D',
    swatches: ['#FAF7F2', '#FFFFFF', '#F4B6B6'],
  },
  'pastel': {
    name: 'Pastel',
    free: true,
    bg: '#FBF1F4',
    surface: '#FFFFFF',
    surfaceAlt: '#F4E7EE',
    ink: '#3a2a3a',
    muted: 'rgba(58,42,58,0.55)',
    faint: 'rgba(58,42,58,0.08)',
    accent: '#C7B8FF',
    accentInk: '#4a3d8a',
    cardFront: '#FFFFFF',
    cardBack: '#F0E8FF',
    glyph: null,
    errorRed: '#E5484D',
    swatches: ['#FBF1F4', '#FFFFFF', '#C7B8FF'],
  },
  'dark': {
    name: 'Dark Mode',
    free: true,
    bg: '#15161A',
    surface: '#1E2026',
    surfaceAlt: '#23262E',
    ink: '#F2F0EB',
    muted: 'rgba(242,240,235,0.55)',
    faint: 'rgba(242,240,235,0.08)',
    accent: '#F4B6B6',
    accentInk: '#15161A',
    cardFront: '#23262E',
    cardBack: '#2A2E37',
    glyph: null,
    errorRed: '#FF6B6B',
    swatches: ['#15161A', '#1E2026', '#F4B6B6'],
  },
  'cats': {
    name: 'Cute Cats',
    free: false,
    bg: '#FFF4E8',
    surface: '#FFFFFF',
    surfaceAlt: '#FFE8D2',
    ink: '#4a2e1a',
    muted: 'rgba(74,46,26,0.55)',
    faint: 'rgba(74,46,26,0.08)',
    accent: '#FF9F6B',
    accentInk: '#FFFFFF',
    cardFront: '#FFFFFF',
    cardBack: '#FFEFE0',
    glyph: '🐱',
    errorRed: '#E5484D',
    swatches: ['#FFF4E8', '#FFFFFF', '#FF9F6B'],
  },
  'dogs': {
    name: 'Cute Dogs',
    free: false,
    bg: '#F3EDE1',
    surface: '#FFFFFF',
    surfaceAlt: '#E8DFCB',
    ink: '#3d2e1f',
    muted: 'rgba(61,46,31,0.55)',
    faint: 'rgba(61,46,31,0.08)',
    accent: '#C28A50',
    accentInk: '#FFFFFF',
    cardFront: '#FFFFFF',
    cardBack: '#F5EBD8',
    glyph: '🐶',
    errorRed: '#E5484D',
    swatches: ['#F3EDE1', '#FFFFFF', '#C28A50'],
  },
  'ocean': {
    name: 'Ocean',
    free: false,
    bg: '#E8F1F5',
    surface: '#FFFFFF',
    surfaceAlt: '#D4E5EE',
    ink: '#0F2A3D',
    muted: 'rgba(15,42,61,0.55)',
    faint: 'rgba(15,42,61,0.08)',
    accent: '#5BA4C7',
    accentInk: '#FFFFFF',
    cardFront: '#FFFFFF',
    cardBack: '#E0EEF5',
    glyph: '🌊',
    errorRed: '#E5484D',
    swatches: ['#E8F1F5', '#FFFFFF', '#5BA4C7'],
  },
  'bakery': {
    name: 'Bakery',
    free: false,
    bg: '#FBEFE0',
    surface: '#FFFFFF',
    surfaceAlt: '#F2E0CA',
    ink: '#5a3a1f',
    muted: 'rgba(90,58,31,0.55)',
    faint: 'rgba(90,58,31,0.08)',
    accent: '#D88E5A',
    accentInk: '#FFFFFF',
    cardFront: '#FFFFFF',
    cardBack: '#FFF1DE',
    glyph: '🥐',
    errorRed: '#E5484D',
    swatches: ['#FBEFE0', '#FFFFFF', '#D88E5A'],
  },
  'japanese': {
    name: 'Japanese Minimal',
    free: false,
    bg: '#F5F0E8',
    surface: '#FFFEFB',
    surfaceAlt: '#EAE2D2',
    ink: '#1a1a1a',
    muted: 'rgba(26,26,26,0.55)',
    faint: 'rgba(26,26,26,0.08)',
    accent: '#B53A3A',
    accentInk: '#FFFEFB',
    cardFront: '#FFFEFB',
    cardBack: '#F5F0E8',
    glyph: '禅',
    errorRed: '#E5484D',
    swatches: ['#F5F0E8', '#FFFEFB', '#B53A3A'],
  },
};

export const THEME_ORDER = ['minimal-white', 'pastel', 'dark', 'cats', 'dogs', 'ocean', 'bakery', 'japanese'];

// Default theme key
export const DEFAULT_THEME = 'minimal-white';

// Accent palette for deck colors (cycles)
export const ACCENT_PALETTE = ['#F4B6B6', '#A8D5BA', '#F4D58D', '#B8D4F4', '#D4B8F4'];

export const radius = { card: 22, input: 14 };

// For backwards compat — export the default theme as `theme`
export const theme = THEMES['minimal-white'];
